# Generated by Django 5.2.8 on 2025-11-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.TextField(blank=True, null=True, unique=True)),
                ('date_time', models.TextField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('barcode', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('receipt', models.ForeignKey(db_column='receipt_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
